import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { calls } from "../../data/callFakes";

import { useNotifications } from "reapop";
import Map from "../../components/Map/Mapview";
import Map2 from "../../components/Map/Mapview2";
import Notificacion from "../../components/Notifications.tsx/Notification";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(0);
  const [locations, setLocations] = useState<any>([]);
  const [incomingCalls, setIncomingCalls] = useState<Record<string, string>>();

  useEffect(() => {
    let interval: NodeJS.Timeout;

    if (count < calls.length) {
      interval = setInterval(() => {
        setCount((count) => count + 1);
        setIncomingCalls(calls[count]);
        const coordinates = calls[count].coordinates.split(",");
        setLocations([
          ...locations,
          { lat: parseFloat(coordinates[0]), lng: parseFloat(coordinates[1]) },
        ]);
      }, 3000);
    }

    return () => clearInterval(interval);
  }, [count]);

  return (
    <>
      <Head>
        <title>
          {incomingCalls
            ? incomingCalls.user_name + " necesita ayuda"
            : "S.O. S"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Notificacion incomingCalls={incomingCalls} />
        {/*<Map locations={locations} />*/}
        <Map2 locations={locations} />
      </main>
    </>
  );
}
